# Generated by Django 2.0.2 on 2020-05-20 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jtsb1',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('时间', models.DateTimeField(auto_now_add=True)),
                ('A相电压', models.FloatField(default=0)),
                ('B相电压', models.FloatField(default=0)),
                ('C相电压', models.FloatField(default=0)),
                ('A相电流', models.FloatField(default=0)),
                ('B相电流', models.FloatField(default=0)),
                ('C相电流', models.FloatField(default=0)),
                ('总有功电度', models.FloatField(default=0)),
                ('总无功电度', models.FloatField(default=0)),
                ('当月有功电度', models.FloatField(default=0)),
                ('当月无功电度', models.FloatField(default=0)),
                ('环境温度1', models.FloatField(default=0)),
                ('环境温度2', models.FloatField(default=0)),
                ('环境温度3', models.FloatField(default=0)),
                ('环境温度4', models.FloatField(default=0)),
                ('环境温度5', models.FloatField(default=0)),
                ('环境温度6', models.FloatField(default=0)),
                ('环境温度7', models.FloatField(default=0)),
                ('环境温度8', models.FloatField(default=0)),
                ('环境温度9', models.FloatField(default=0)),
                ('环境温度10', models.FloatField(default=0)),
                ('环境温度11', models.FloatField(default=0)),
                ('环境温度12', models.FloatField(default=0)),
                ('环境湿度1', models.FloatField(default=0)),
                ('环境湿度2', models.FloatField(default=0)),
                ('flag1', models.IntegerField(null=True)),
                ('flag2', models.IntegerField(null=True)),
                ('flag3', models.IntegerField(null=True)),
                ('flag4', models.IntegerField(null=True)),
            ],
            options={
                'db_table': 'jtsb1',
            },
        ),
    ]
