# Generated by Django 2.0.2 on 2020-05-20 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brl', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtsb1',
            name='时间',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
