# Generated by Django 2.0.2 on 2020-05-20 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brl', '0002_auto_20200520_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jtsb1',
            name='A相电压',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='A相电流',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='B相电压',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='B相电流',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='C相电压',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='C相电流',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='当月无功电度',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='当月有功电度',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='总无功电度',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='总有功电度',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度10',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度11',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度12',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度2',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度3',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度4',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度5',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度6',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度7',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度8',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境温度9',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境湿度1',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='jtsb1',
            name='环境湿度2',
            field=models.FloatField(default=0, null=True),
        ),
    ]
