# Generated by Django 2.0.2 on 2020-05-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brl', '0003_auto_20200520_1635'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'shebei_name1',
            },
        ),
    ]
